export const TYPOGRAPHY = {
  // Font families
  FONT_FAMILY_HEADER: 'Georgia, serif',
  FONT_FAMILY_BODY: 'System',
  FONT_FAMILY_MONO: 'Courier New, monospace',
  
  // Font sizes
  FONT_SIZE_XS: 12,
  FONT_SIZE_SM: 14,
  FONT_SIZE_MD: 16,
  FONT_SIZE_LG: 18,
  FONT_SIZE_XL: 20,
  FONT_SIZE_XXL: 24,
  FONT_SIZE_XXXL: 32,
  FONT_SIZE_HERO: 48,
  
  // Line heights
  LINE_HEIGHT_TIGHT: 1.2,
  LINE_HEIGHT_NORMAL: 1.5,
  LINE_HEIGHT_RELAXED: 1.8,
  
  // Font weights
  FONT_WEIGHT_LIGHT: '300',
  FONT_WEIGHT_NORMAL: '400',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_SEMIBOLD: '600',
  FONT_WEIGHT_BOLD: '700',
  
  // Letter spacing
  LETTER_SPACING_TIGHT: -0.5,
  LETTER_SPACING_NORMAL: 0,
  LETTER_SPACING_WIDE: 1,
  LETTER_SPACING_WIDER: 2,
} as const;

export const TEXT_STYLES = {
  // Header styles
  H1: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_XXXL,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.FONT_SIZE_XXXL * TYPOGRAPHY.LINE_HEIGHT_TIGHT,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_TIGHT,
  },
  H2: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_XXL,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMIBOLD,
    lineHeight: TYPOGRAPHY.FONT_SIZE_XXL * TYPOGRAPHY.LINE_HEIGHT_TIGHT,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_TIGHT,
  },
  H3: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_XL,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.FONT_SIZE_XL * TYPOGRAPHY.LINE_HEIGHT_NORMAL,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_NORMAL,
  },
  H4: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_LG,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.FONT_SIZE_LG * TYPOGRAPHY.LINE_HEIGHT_NORMAL,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_NORMAL,
  },
  
  // Body text styles
  BODY_LARGE: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_BODY,
    fontSize: TYPOGRAPHY.FONT_SIZE_LG,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_NORMAL,
    lineHeight: TYPOGRAPHY.FONT_SIZE_LG * TYPOGRAPHY.LINE_HEIGHT_RELAXED,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_NORMAL,
  },
  BODY: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_BODY,
    fontSize: TYPOGRAPHY.FONT_SIZE_MD,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_NORMAL,
    lineHeight: TYPOGRAPHY.FONT_SIZE_MD * TYPOGRAPHY.LINE_HEIGHT_RELAXED,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_NORMAL,
  },
  BODY_SMALL: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_BODY,
    fontSize: TYPOGRAPHY.FONT_SIZE_SM,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_NORMAL,
    lineHeight: TYPOGRAPHY.FONT_SIZE_SM * TYPOGRAPHY.LINE_HEIGHT_RELAXED,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_NORMAL,
  },
  
  // Special text styles
  LITURGICAL: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_MD,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_NORMAL,
    lineHeight: TYPOGRAPHY.FONT_SIZE_MD * TYPOGRAPHY.LINE_HEIGHT_RELAXED,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_WIDE,
    fontStyle: 'italic',
  },
  PRAYER: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_HEADER,
    fontSize: TYPOGRAPHY.FONT_SIZE_LG,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_NORMAL,
    lineHeight: TYPOGRAPHY.FONT_SIZE_LG * TYPOGRAPHY.LINE_HEIGHT_RELAXED,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_WIDE,
  },
  CAPTION: {
    fontFamily: TYPOGRAPHY.FONT_FAMILY_BODY,
    fontSize: TYPOGRAPHY.FONT_SIZE_XS,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_LIGHT,
    lineHeight: TYPOGRAPHY.FONT_SIZE_XS * TYPOGRAPHY.LINE_HEIGHT_NORMAL,
    letterSpacing: TYPOGRAPHY.LETTER_SPACING_WIDE,
  },
} as const;
